export const word1 = [
    ["mouth", "рот"],
    ["wireless", "беспроводной"],
    ["communication", "связь"],
    ["permission", "разрешение"],
    ["entries", "записи"],
    ["range", "Диапазон"],
    ["select", "выделить"],
    ["skeuomorph", "скевоморфизм"],
    ["template", "шаблон"],
    ["convert", "преобразовать"],
    ["append", "добавлять"],
    ["release", "освобождать"],
    ["caught", "пойманный"],
    ["found", "нашел"],
    ["collapse", "коллапс"],
    ["persistence", "упорство"],
    ["instance", "пример"],
    ["compare", "сравнивать"],
    ["mailing", "рассылка"],
    ["adjusted", "настроенный"],
    ["layout", "верстка"],
    ["turn", "очередь"],
    ["turning", "превращение"],
    ["fairing", "обтекатель"],
    ["sequence", "последовательность"],
    ["spacers", "распорки"],
    ["unknown", "неизвестный"],
    ["several", "несколько"],
    ["contains", "содержит"],
    ["mount", "монтировать"],
    ["wrapper", "обертка"],
    ["configure", "настроить"],
    ["blur", "пятно"],
    ["required", "требуемый"]
]


export const word2 = [
    ["accept", "принять"],
    ["agree", "согласиться"],
    ["application", "приложение"],
    ["attend", "посещать"],
    ["become", "становиться"],
    ["boost", "улучшить"],
    ["challenge", "вызов"],
    ["check", "проверить"],
    ["code", "писать код"],
    ["condition", "условие"],
    ["corker", "сотрудник"],
    ["develop", "развивать"],
    ["expect", "ожидать"],
    ["fail", "провалить"],
    ["goal", "цель"],
    ["vocabulary", "запас слов"],
    ["growth", "рост"],
    ["hire", "нанимать"],
    ["insurance", "страховка"],
    ["interoperability", "совместимость"],
    ["issue", "проблема"],
    ["match", "подходить"],
    ["overtime", "сверхурочно"],
    ["previous", "предыдущий"],
    ["resolve", "решать"],
    ["salary", "зарплата"],
    ["space", "место"],
    ["weakness", "слабость"],
    ["CEO", "главный исполнительный директор"],
    ["CFO", "финансовый директор"],
    ["CIO", "директор по информации"],
    ["CTO", "главный технический директор"],
    ["analyst", "аналитик"],
    ["architect", "архитектор"],
    ["build", "построить"],
    ["cooperate", "сотрудничать"],
    ["department", "отдел"],
    ["developer", "разработчик"],
    ["join", "присоединиться"],
    ["objective", "задача"],
    ["owner", "хозяин"],
    ["powerful", "мощный"],
    ["produce", "производить"],
    ["product", "продуктовый"],
    ["programmer", "программист"],
    ["relationship", "отношения"],
    ["restore", "восстановить"],
    ["senior", "старший"],
    ["strong", "сильный"],
    ["support", "поддерживать"],
    ["trust", "доверять"],
    ["webmaster", "разработчик сайта"],
    ["agenda", "повестка дня"],
    ["appointment", "встреча"],
    ["arrange", "организовать"],
    ["catch", "расслышать"],
    ["conclusion", "вывод"],
    ["congratulations", "поздравления"],
    ["consider", "рассмотреть"],
    ["contact", "связываться"],
    ["dial", "набрать"],
    ["enclosed", "прикрепленный"],
    ["engaged", "занятой"],
    ["enquire", "узнать"],
    ["exchange", "обменяться"],
    ["extension", "добавочный номер"],
    ["inform", "сообщить"],
    ["introduce", "представить"],
    ["leave", "оставить"],
    ["order", "заказать"],
    ["reply", "отвечать"],
    ["respect", "уважать"],
    ["spell", "произнести по буквам"],
    ["target", "цель"],
    ["voicemail", "голосовая почта"],
    ["LMAO", "пацталом"],
    ["LOL", "ржунимагу"],
    ["appreciate", "высоко ценить"],
    ["attached", "прикрепленный"],
    ["beginning", "начало"],
    ["clarify", "прояснить"],
    ["clear", "ясный"],
    ["complain", "жаловаться"],
    ["confirm", "подтвердить"],
    ["emphasise", "подчеркнуть"],
    ["ending", "окончание"],
    ["highlight", "выделять"],
    ["ignore", "пропускать"],
    ["inbox", "входящие"],
    ["let", "позволять"],
    ["message", "сообщение"],
    ["receive", "получать"],
    ["regarding", "по теме"],
    ["regret", "сожалеть"],
    ["report", "отчет"],
    ["request", "попросить"],
    ["sign", "подписать"],
    ["template", "шаблон"],
    ["title", "заголовок"],
    ["trash", "корзина"],
    ["volume", "объем"],
    ["adjusted", "настроенный"],
    ["brief", "краткий"],
    ["displayed", "отображаемый"],
    ["functional", "функциональный"],
    ["possible", "возможный"],
    ["reliable", "надежный"],
    ["carefully", "тщательно"],
    ["backup", "резервная копия"],
    ["content", "наполнение"],
    ["database", "база данных"],
    ["discretion", "усмотрение"],
    ["disk ota", "дисковая квота"],
    ["domain", "домен"],
    ["fixing", "исправление"],
    ["compatibility", "совместимость"],
    ["form", "форма"],
    ["maintenance", "техобслуживание"],
    ["purpose", "назначение"],
    ["requirements", "требования"],
    ["responsibilities", "обязанности"],
    ["specification", "особенность"],
    ["term", "условие"],
    ["cover", "описывать"],
    ["edit", "редактировать"],
    ["establish", "устанавливать"],
    ["indicate", "указать"],
    ["itemize", "составить перечень"],
    ["launch", "запускать"],
    ["remove", "убрать"],
    ["conclude", "сделать вывод"],
    ["estimate", "оценивать"],
    ["mean", "иметь в виду"],
    ["mention", "упоминать"],
    ["outline", "очертить"],
    ["recap", "резюмировать"],
    ["refer", "ссылаться"],
    ["share", "поделиться"],
    ["acceptable", "приемлемый"],
    ["instead", "вместо"],
    ["notes", "записи"],
    ["briefly", "кратко"],
    ["completely", "полностью"],
    ["currently", "на данный момент"],
    ["deeply", "детально"],
    ["directly", "напрямую"],
    ["especially", "особенно"],
    ["extremely", "очень"],
    ["likely", "похоже"],
    ["mainly", "в основном"],
    ["obviously", "очевидно"],
    ["properly", "непосредственно"],
    ["quite", "довольно"],
    ["really", "действительно"],
    ["slightly", "слегка"],
    ["totally", "полностью"],
    ["milestone", "этап работы"],
    ["occasion", "событие"],
    ["stakeholders", "заинтересованные стороны"],
    ["enthusiastic", "полный энергии"],
    ["exhausted", "изнуренный"],
    ["sufficient", "достаточный"],
    ["trustworthy", "надежный"],
    ["significantly", "значительно"],
    ["timely", "своевременно"],
    ["align", "упорядочить"],
    ["allot", "назначать"],
    ["broaden", "расширить"],
    ["creep", "подкрадываться"],
    ["delay", "задерживать"],
    ["determine", "определять"],
    ["ensure", "обеспечить"],
    ["forecast", "предугадывать"],
    ["oversight", "контролировать"],
    ["proceed", "продолжить"],
    ["shift", "сдвигать"],
    ["streamline", "упрощать"],
    ["waste", "тратить зря"],
    ["anxious", "встревоженный"],
    ["competitive", "соревновательный"],
    ["distressed", "беспокойный"],
    ["hostile", "враждебный"],
    ["irritated", "раздраженный"],
    ["patient", "терпеливый"],
    ["anticipate", "предвидеть"],
    ["blame", "винить"],
    ["cause", "причинять"],
    ["derail", "срывать"],
    ["gossip", "сплетня"],
    ["rat", "ce - крысиные бега"],
    ["redundancy", "сокращение"],
    ["rival", "соперник"],
    ["avoid", "избегать"],
    ["exasperate", "выводить из себя"],
    ["handle", "справляться"],
    ["inspire", "вдохновлять"],
    ["outweigh", "превзойти"],
    ["relaunch", "перезапускать"],
    ["remain", "оставаться"],
    ["resign", "уволиться"],
    ["retrain", "переобучать"],
    ["struggle", "сражаться"],
    ["suffer", "страдать"],
    ["survive", "выживать"],
    ["benchmark", "критерий"],
    ["bootstrapping", "самораскрутка финансирование"],
    ["founder", "учредитель"],
    ["loan", "заем финансирование"],
    ["middleware", "межплатформенное ПО инвестиций"],
    ["revenue", "доход капитал"],
    ["vesting", "передача права"],
    ["compelling", "убедительный"],
    ["crucial", "решающий"],
    ["flawless", "безупречный"],
    ["sustainable", "устойчивый"],
    ["tremendous", "колоссальный"],
    ["viable", "жизнеспособный"],
    ["alter", "видоизменять"],
    ["bankroll", "спонсировать"],
    ["overrule", "отклонить"],
    ["reinforce", "усилить"],
    ["underlie", "лежать в основе"],
]

export const word3 = [
    ["beg pardon", "просить прощения"],
    ["long-term", "долгосрочный"],
    ["venture capital", "предпринимательский"],
    ["ground floor", "начальный этап"],
    ["mezzanine financing", "дополнительное"],
    ["cost variance", "отклонения от затрат"],
    ["debt financing", "привлечение кредитования"],
    ["due diligence", "комплексная юроценка"],
    ["elevator speech", "краткая презентация"],
    ["equity financing", "акционерное"],
    ["cloud ware", "облачное ПО"],
    ["bleeding edge", "новейший продукт"],
    ["time off", "передышка"],
    ["cope with", "справляться"],
    ["figure out", "придумать"],
    ["give up", "бросить"],
    ["keep within", "придерживаться"],
    ["carry out", "выполнить"],
    ["veer off", "отклониться"],
    ["time frame", "отрезок времени"],
    ["route map", "дорожная карта"],
    ["due date", "срок окончания"],
    ["frantic pace", "бешеный темп"],
    ["visual aids", "наглядные пособия"],
    ["sum up", "подбить итоги"],
    ["move on", "двигаться дальше"],
    ["beta test", "опытная эксплуатация"],
    ["look forward", "ждать с нетерпением"],
    ["main point", "главная часть"],
    ["send back", "отправить обратно"],
    ["on behalf", "от имени"],
    ["ring up", "позвонить"],
    ["mail shots", "почтовая рассылка"],
    ["put through", "соединить"],
    ["read back", "повторить записанное"],
    ["on time", "вовремя"],
    ["sick leave", "больничный"],
    ["deal with", "иметь дело"],
    ["product manager", "менеджер по продукту"],
    ["get on", "ладить"],
    ["project manager", "менеджер проекта"],
    ["systems administrator", "системный администратор"],
    ["systems director", "директор по управлению системами"],
    ["call back", "перезвонить"],
    ["find out", "узнать"],
    ["hold on", "ожидать"],
    ["to-do list", "список дел"],
    ["proof of concept", "проверка концепции"],
    ["return on investment", "эффективность"],
]

export const words1 = [
    ["hasAuthority", "имеетВласть"],
    ["UserDetailsService", "ПользовательПодробностиУслуга"],
    ["UserService", "ПользовательУслуга"],
    ["shutdownGracefully", "неисправностьИзящно"],
    ["ServerBootstrap", "сервер начальная загрузка"],
    ["EventLoopGroup", "СобытиПпетляГруппа"]
]






